// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentsFormController from "./comments_form_controller"
application.register("comments-form", CommentsFormController)

import MentionsController from "./mentions_controller"
application.register("mentions", MentionsController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)
